services:
  asr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: melvin-asr
    volumes:
      - ./models:/asr/models
      - ./data:/asr/data
      - ./config.yml:/asr/config.yml
    ports:
      - "8393:8393"
      - "8394:8394"
