services:
  asr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: melvin-asr
    volumes:
      - ./data:/melvin-asr/data
      - ./config.yml:/melvin-asr/config.yml:ro
    ports:
      - "8000:8000"

    # # Use the following part to utilize GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ["0"]
    #           capabilities: [gpu]
