SUPPORTED_LANGUAGES = {
    "af": "afr",
    "am": "amh",
    "ar": "arb",
    "as": "asm",
    "az": "azj",
    "ba": "bak",
    "be": "bel",
    "bg": "bul",
    "bn": "ben",
    "bo": "bod",
    "br": "bre",
    "bs": "bos",
    "ca": "cat",
    "cs": "ces",
    "cy": "cym",
    "da": "dan",
    "de": "deu",
    "el": "ell",
    "en": "eng",
    "es": "spa",
    "et": "est",
    "eu": "eus",
    "fa": "pes",
    "fi": "fin",
    "fo": "fao",
    "fr": "fra",
    "gl": "glg",
    "gu": "guj",
    "ha": "hau",
    "haw": "haw",
    "he": "heb",
    "hi": "hin",
    "hr": "hrv",
    "ht": "hat",
    "hu": "hun",
    "hy": "hye",
    "id": "ind",
    "is": "isl",
    "it": "ita",
    "ja": "jpn",
    "jw": "jav",
    "ka": "kat",
    "kk": "kaz",
    "km": "khm",
    "kn": "kan",
    "ko": "kor",
    "la": "lat",
    "lb": "ltz",
    "ln": "lin",
    "lo": "lao",
    "lt": "lit",
    "lv": "lvs",
    "mg": "mlg",
    "mi": "mri",
    "mk": "mkd",
    "ml": "mal",
    "mn": "khk",
    "mr": "mar",
    "ms": "zsm",
    "mt": "mlt",
    "my": "mya",
    "ne": "npi",
    "nl": "nld",
    "nn": "nno",
    "no": "nob",
    "oc": "oci",
    "pa": "pan",
    "pl": "pol",
    "ps": "pbt",
    "pt": "por",
    "ro": "ron",
    "ru": "rus",
    "sa": "san",
    "sd": "snd",
    "si": "sin",
    "sk": "slk",
    "sl": "slv",
    "sn": "sna",
    "so": "som",
    "sq": "sqi",
    "sr": "srp",
    "su": "sun",
    "sv": "swe",
    "sw": "swh",
    "ta": "tam",
    "te": "tel",
    "tg": "tgk",
    "th": "tha",
    "tk": "tuk",
    "tl": "tgl",
    "tr": "tur",
    "tt": "tat",
    "uk": "ukr",
    "ur": "urd",
    "uz": "uzn",
    "vi": "vie",
    "yi": "yid",
    "yo": "yor",
    "zh": "cmn_Hant",
    "cn": "cmn",
}

def get_supported_languages() -> list[str]:
    return list(SUPPORTED_LANGUAGES.keys())

def is_language_supported(language: str) -> bool:
    return language in SUPPORTED_LANGUAGES

def map_language_code(language: str) -> str:
    if language not in SUPPORTED_LANGUAGES:
        raise ValueError(f"Language {language} is not supported.")
    return SUPPORTED_LANGUAGES[language]