LANGUAGE_CODES = {
    "af": ["afr"],
    "am": ["amh"],
    "ar": ["arb", "ary", "arz"],
    "as": ["asm"],
    "az": ["azj"],
    "be": ["bel"],
    "bg": ["bul"],
    "bn": ["ben"],
    "bs": ["bos"],
    "ca": ["cat"],
    "ceb": ["ceb"],
    "cs": ["ces"],
    "cy": ["cym"],
    "da": ["dan"],
    "de": ["deu"],
    "el": ["ell"],
    "en": ["eng"],
    "es": ["spa"],
    "et": ["est"],
    "eu": ["eus"],
    "fa": ["pes"],
    "ff": ["fuv"],
    "fi": ["fin"],
    "fr": ["fra"],
    "ga": ["gle"],
    "gl": ["glg"],
    "gu": ["guj"],
    "he": ["heb"],
    "hi": ["hin"],
    "hr": ["hrv"],
    "hu": ["hun"],
    "hy": ["hye"],
    "id": ["ind"],
    "ig": ["ibo"],
    "is": ["isl"],
    "it": ["ita"],
    "ja": ["jpn"],
    "jv": ["jav"],
    "ka": ["kat"],
    "kk": ["kaz"],
    "km": ["khm"],
    "kn": ["kan"],
    "ko": ["kor"],
    "ku": ["ckb"],
    "ky": ["kir"],
    "lg": ["lug"],
    "lo": ["lao"],
    "lt": ["lit"],
    "luo": ["luo"],
    "lv": ["lvs"],
    "mk": ["mkd"],
    "ml": ["mal"],
    "mn": ["khk"],
    "mr": ["mar"],
    "ms": ["zlm"],
    "mt": ["mlt"],
    "my": ["mya"],
    "nb": ["nob"],
    "ne": ["npi"],
    "nl": ["nld"],
    "nn": ["nno"],
    "ny": ["nya"],
    "or": ["ory"],
    "pa": ["pan"],
    "pl": ["pol"],
    "ps": ["pbt"],
    "pt": ["por"],
    "ro": ["ron"],
    "ru": ["rus"],
    "sd": ["snd"],
    "sk": ["slk"],
    "sl": ["slv"],
    "sn": ["sna"],
    "so": ["som"],
    "sr": ["srp"],
    "sv": ["swe"],
    "sw": ["swh"],
    "ta": ["tam"],
    "te": ["tel"],
    "tg": ["tgk"],
    "th": ["tha"],
    "tl": ["tgl"],
    "tr": ["tur"],
    "uk": ["ukr"],
    "ur": ["urd"],
    "uz": ["uzn"],
    "vi": ["vie"],
    "yo": ["yor"],
    "yue": ["yue"],
    "zh": ["cmn", "cmn_Hant"],
    "zu": ["zul"],
    # "gaz": ["gaz"], # Gaz language does not have an ISO 639-1 code
    # "mai": ["mai"], # Maithili language does not have an ISO 639-1 code
    # "mni": ["mni"], # Manipuri language does not have an ISO 639-1 code
    # "sat": ["sat"], # Santali language does not have an ISO 639-1 code
}


SUPPORTED_LANGUAGES = {
    "af": "afr",
    "am": "amh",
    "ar": "arb",
    "as": "asm",
    "az": "azj",
    "ba": "bak",
    "be": "bel",
    "bg": "bul",
    "bn": "ben",
    "bo": "bod",
    "br": "bre",
    "bs": "bos",
    "ca": "cat",
    "cn": "cmn",
    "cs": "ces",
    "cy": "cym",
    "da": "dan",
    "de": "deu",
    "el": "ell",
    "en": "eng",
    "es": "spa",
    "et": "est",
    "eu": "eus",
    "fa": "pes",
    "fi": "fin",
    "fo": "fao",
    "fr": "fra",
    "gl": "glg",
    "gu": "guj",
    "ha": "hau",
    "haw": "haw",
    "he": "heb",
    "hi": "hin",
    "hr": "hrv",
    "ht": "hat",
    "hu": "hun",
    "hy": "hye",
    "id": "ind",
    "is": "isl",
    "it": "ita",
    "ja": "jpn",
    "jw": "jav",
    "ka": "kat",
    "kk": "kaz",
    "km": "khm",
    "kn": "kan",
    "ko": "kor",
    "la": "lat",
    "lb": "ltz",
    "ln": "lin",
    "lo": "lao",
    "lt": "lit",
    "lv": "lvs",
    "mg": "mlg",
    "mi": "mri",
    "mk": "mkd",
    "ml": "mal",
    "mn": "khk",
    "mr": "mar",
    "ms": "zsm",
    "mt": "mlt",
    "my": "mya",
    "ne": "npi",
    "nl": "nld",
    "nn": "nno",
    "no": "nob",
    "oc": "oci",
    "pa": "pan",
    "pl": "pol",
    "ps": "pbt",
    "pt": "por",
    "ro": "ron",
    "ru": "rus",
    "sa": "san",
    "sd": "snd",
    "si": "sin",
    "sk": "slk",
    "sl": "slv",
    "sn": "sna",
    "so": "som",
    "sq": "sqi",
    "sr": "srp",
    "su": "sun",
    "sv": "swe",
    "sw": "swh",
    "ta": "tam",
    "te": "tel",
    "tg": "tgk",
    "th": "tha",
    "tk": "tuk",
    "tl": "tgl",
    "tr": "tur",
    "tt": "tat",
    "uk": "ukr",
    "ur": "urd",
    "uz": "uzn",
    "vi": "vie",
    "yi": "yid",
    "yo": "yor",
    "zh": "cmn_Hant",
}

def get_supported_languages() -> list[str]:
    return list(SUPPORTED_LANGUAGES.keys())

def is_language_supported(language: str) -> bool:
    return language in SUPPORTED_LANGUAGES

def map_language_code(language: str) -> str:
    if language not in SUPPORTED_LANGUAGES:
        raise ValueError(f"Language {language} is not supported.")
    return SUPPORTED_LANGUAGES[language][0]  # Return the first code in the list