LANGUAGE_CODES = {
    "af": ["afr"],
    "am": ["amh"],
    "ar": ["arb", "ary", "arz"],
    "as": ["asm"],
    "az": ["azj"],
    "be": ["bel"],
    "bg": ["bul"],
    "bn": ["ben"],
    "bs": ["bos"],
    "ca": ["cat"],
    "ceb": ["ceb"],
    "cs": ["ces"],
    "cy": ["cym"],
    "da": ["dan"],
    "de": ["deu"],
    "el": ["ell"],
    "en": ["eng"],
    "es": ["spa"],
    "et": ["est"],
    "eu": ["eus"],
    "fa": ["pes"],
    "ff": ["fuv"],
    "fi": ["fin"],
    "fr": ["fra"],
    "ga": ["gle"],
    "gl": ["glg"],
    "gu": ["guj"],
    "he": ["heb"],
    "hi": ["hin"],
    "hr": ["hrv"],
    "hu": ["hun"],
    "hy": ["hye"],
    "id": ["ind"],
    "ig": ["ibo"],
    "is": ["isl"],
    "it": ["ita"],
    "ja": ["jpn"],
    "jv": ["jav"],
    "ka": ["kat"],
    "kk": ["kaz"],
    "km": ["khm"],
    "kn": ["kan"],
    "ko": ["kor"],
    "ku": ["ckb"],
    "ky": ["kir"],
    "lg": ["lug"],
    "lo": ["lao"],
    "lt": ["lit"],
    "luo": ["luo"],
    "lv": ["lvs"],
    "mk": ["mkd"],
    "ml": ["mal"],
    "mn": ["khk"],
    "mr": ["mar"],
    "ms": ["zlm"],
    "mt": ["mlt"],
    "my": ["mya"],
    "nb": ["nob"],
    "ne": ["npi"],
    "nl": ["nld"],
    "nn": ["nno"],
    "ny": ["nya"],
    "or": ["ory"],
    "pa": ["pan"],
    "pl": ["pol"],
    "ps": ["pbt"],
    "pt": ["por"],
    "ro": ["ron"],
    "ru": ["rus"],
    "sd": ["snd"],
    "sk": ["slk"],
    "sl": ["slv"],
    "sn": ["sna"],
    "so": ["som"],
    "sr": ["srp"],
    "sv": ["swe"],
    "sw": ["swh"],
    "ta": ["tam"],
    "te": ["tel"],
    "tg": ["tgk"],
    "th": ["tha"],
    "tl": ["tgl"],
    "tr": ["tur"],
    "uk": ["ukr"],
    "ur": ["urd"],
    "uz": ["uzn"],
    "vi": ["vie"],
    "yo": ["yor"],
    "yue": ["yue"],
    "zh": ["cmn", "cmn_Hant"],
    "zu": ["zul"],
    # "gaz": ["gaz"], # Gaz language does not have an ISO 639-1 code
    # "mai": ["mai"], # Maithili language does not have an ISO 639-1 code
    # "mni": ["mni"], # Manipuri language does not have an ISO 639-1 code
    # "sat": ["sat"], # Santali language does not have an ISO 639-1 code
}


def get_supported_languages() -> list[str]:
    return list(LANGUAGE_CODES.keys())

def is_language_supported(language: str) -> bool:
    return language in LANGUAGE_CODES

def map_language_code(language: str) -> str:
    if language not in LANGUAGE_CODES:
        raise ValueError(f"Language {language} is not supported.")
    return LANGUAGE_CODES[language][0]  # Return the first code in the list