name: Lint & Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: 5.1

      - name: Lint src with Ruff
        run: ruff check ./src

      - name: Lint tooling with Ruff
        run: ruff check ./tooling

      - name: Run PyTest
        run: pytest --cov=src

      - name: Test Code Coverage /src
        run: coverage report --fail-under=70

